"""add specialty and topic to step_problem

Revision ID: 3312fc310644
Revises: 557539feb59c
Create Date: 2026-03-29 13:00:26.594199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3312fc310644'
down_revision: Union[str, None] = '557539feb59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_problems', sa.Column('specialty', sa.String(), nullable=True))
    op.add_column('step_problems', sa.Column('topic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step_problems', 'topic')
    op.drop_column('step_problems', 'specialty')
    # ### end Alembic commands ###