"""board has one step, simplify board_users

Revision ID: 4528061ea8ec
Revises: be920b7aff18
Create Date: 2026-03-29 20:29:49.732923

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4528061ea8ec"
down_revision: Union[str, None] = "be920b7aff18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "board_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("board_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("board_id", "user_id", name="uq_board_user"),
    )
    op.create_index(
        op.f("ix_board_users_board_id"), "board_users", ["board_id"], unique=False
    )
    op.create_index(op.f("ix_board_users_id"), "board_users", ["id"], unique=False)
    op.create_index(
        op.f("ix_board_users_user_id"), "board_users", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_board_step_users_board_id"), table_name="board_step_users")
    op.drop_index(op.f("ix_board_step_users_id"), table_name="board_step_users")
    op.drop_index(op.f("ix_board_step_users_step_id"), table_name="board_step_users")
    op.drop_index(op.f("ix_board_step_users_user_id"), table_name="board_step_users")
    op.drop_table("board_step_users")
    op.add_column("boards", sa.Column("step_id", sa.Integer(), nullable=True))
    op.execute("UPDATE boards SET step_id = (SELECT id FROM steps LIMIT 1)")
    op.alter_column("boards", "step_id", nullable=False)
    op.create_index(op.f("ix_boards_step_id"), "boards", ["step_id"], unique=False)
    op.create_foreign_key(
        None, "boards", "steps", ["step_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "groups", type_="foreignkey")
    op.drop_constraint(None, "boards", type_="foreignkey")
    op.drop_index(op.f("ix_boards_step_id"), table_name="boards")
    op.drop_column("boards", "step_id")
    op.create_table(
        "board_step_users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("board_id", sa.INTEGER(), nullable=False),
        sa.Column("step_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["step_id"], ["steps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "board_id", "step_id", "user_id", name=op.f("uq_board_step_user")
        ),
    )
    op.create_index(
        op.f("ix_board_step_users_user_id"),
        "board_step_users",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_board_step_users_step_id"),
        "board_step_users",
        ["step_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_board_step_users_id"), "board_step_users", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_board_step_users_board_id"),
        "board_step_users",
        ["board_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_board_users_user_id"), table_name="board_users")
    op.drop_index(op.f("ix_board_users_id"), table_name="board_users")
    op.drop_index(op.f("ix_board_users_board_id"), table_name="board_users")
    op.drop_table("board_users")
    # ### end Alembic commands ###
