"""initial

Revision ID: 557539feb59c
Revises:
Create Date: 2026-03-29 12:11:37.835119

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "557539feb59c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_groups_id"), "groups", ["id"], unique=False)
    op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=True)
    op.create_table(
        "problems",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("problem_id", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "problem_id"),
    )
    op.create_index(op.f("ix_problems_id"), "problems", ["id"], unique=False)
    op.create_index(
        op.f("ix_problems_problem_id"), "problems", ["problem_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("nickname", sa.String(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("is_super_admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "group_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("MEMBER", "ADMIN", name="grouprole"), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "user_id", name="uq_group_user"),
    )
    op.create_index(
        op.f("ix_group_users_group_id"), "group_users", ["group_id"], unique=False
    )
    op.create_index(op.f("ix_group_users_id"), "group_users", ["id"], unique=False)
    op.create_index(
        op.f("ix_group_users_user_id"), "group_users", ["user_id"], unique=False
    )
    op.create_table(
        "solutions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("nickname", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column(
            "result",
            sa.Enum(
                "Accepted",
                "WrongAnswer",
                "TimeLimitExceeded",
                "MemoryLimitExceeded",
                "RuntimeError",
                "OutputLimitExceeded",
                "CompileError",
                "PresentationError",
                "SystemError",
                "Unknown",
                name="resultenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "language",
            sa.Enum(
                "C",
                "Cpp",
                "Python",
                "Java",
                "Go",
                "Rust",
                "JavaScript",
                "TypeScript",
                "CSharp",
                "Pascal",
                "Fortran",
                "Unknown",
                name="languageenum",
            ),
            nullable=True,
        ),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("solution_id", sa.Integer(), nullable=True),
        sa.Column("problem_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_solutions_id"), "solutions", ["id"], unique=False)
    op.create_index(
        op.f("ix_solutions_problem_id"), "solutions", ["problem_id"], unique=False
    )
    op.create_index(
        op.f("ix_solutions_solution_id"), "solutions", ["solution_id"], unique=False
    )
    op.create_index(
        op.f("ix_solutions_submitted_at"), "solutions", ["submitted_at"], unique=False
    )
    op.create_index(
        op.f("ix_solutions_username"), "solutions", ["username"], unique=False
    )
    op.create_table(
        "source_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "username", name="uq_source_username"),
    )
    op.create_index(op.f("ix_source_users_id"), "source_users", ["id"], unique=False)
    op.create_index(
        op.f("ix_source_users_source"), "source_users", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_source_users_user_id"), "source_users", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_users_username"), "source_users", ["username"], unique=False
    )
    op.create_table(
        "steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_steps_created_by"), "steps", ["created_by"], unique=False)
    op.create_index(op.f("ix_steps_group_id"), "steps", ["group_id"], unique=False)
    op.create_index(op.f("ix_steps_id"), "steps", ["id"], unique=False)
    op.create_table(
        "group_step_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("ac_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["step_id"], ["steps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "group_id",
            "user_id",
            "step_id",
            "problem_id",
            name="uq_group_user_step_problem",
        ),
    )
    op.create_index(
        op.f("ix_group_step_progress_group_id"),
        "group_step_progress",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_step_progress_id"), "group_step_progress", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_group_step_progress_problem_id"),
        "group_step_progress",
        ["problem_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_step_progress_step_id"),
        "group_step_progress",
        ["step_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_step_progress_user_id"),
        "group_step_progress",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "step_problems",
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["step_id"], ["steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("step_id", "problem_id"),
        sa.UniqueConstraint("step_id", "problem_id", name="uq_step_problem"),
    )
    op.create_index(
        op.f("ix_step_problems_problem_id"),
        "step_problems",
        ["problem_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_step_problems_step_id"), "step_problems", ["step_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_step_problems_step_id"), table_name="step_problems")
    op.drop_index(op.f("ix_step_problems_problem_id"), table_name="step_problems")
    op.drop_table("step_problems")
    op.drop_index(
        op.f("ix_group_step_progress_user_id"), table_name="group_step_progress"
    )
    op.drop_index(
        op.f("ix_group_step_progress_step_id"), table_name="group_step_progress"
    )
    op.drop_index(
        op.f("ix_group_step_progress_problem_id"), table_name="group_step_progress"
    )
    op.drop_index(op.f("ix_group_step_progress_id"), table_name="group_step_progress")
    op.drop_index(
        op.f("ix_group_step_progress_group_id"), table_name="group_step_progress"
    )
    op.drop_table("group_step_progress")
    op.drop_index(op.f("ix_steps_id"), table_name="steps")
    op.drop_index(op.f("ix_steps_group_id"), table_name="steps")
    op.drop_index(op.f("ix_steps_created_by"), table_name="steps")
    op.drop_table("steps")
    op.drop_index(op.f("ix_source_users_username"), table_name="source_users")
    op.drop_index(op.f("ix_source_users_user_id"), table_name="source_users")
    op.drop_index(op.f("ix_source_users_source"), table_name="source_users")
    op.drop_index(op.f("ix_source_users_id"), table_name="source_users")
    op.drop_table("source_users")
    op.drop_index(op.f("ix_solutions_username"), table_name="solutions")
    op.drop_index(op.f("ix_solutions_submitted_at"), table_name="solutions")
    op.drop_index(op.f("ix_solutions_solution_id"), table_name="solutions")
    op.drop_index(op.f("ix_solutions_problem_id"), table_name="solutions")
    op.drop_index(op.f("ix_solutions_id"), table_name="solutions")
    op.drop_table("solutions")
    op.drop_index(op.f("ix_group_users_user_id"), table_name="group_users")
    op.drop_index(op.f("ix_group_users_id"), table_name="group_users")
    op.drop_index(op.f("ix_group_users_group_id"), table_name="group_users")
    op.drop_table("group_users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_problems_problem_id"), table_name="problems")
    op.drop_index(op.f("ix_problems_id"), table_name="problems")
    op.drop_table("problems")
    op.drop_index(op.f("ix_groups_name"), table_name="groups")
    op.drop_index(op.f("ix_groups_id"), table_name="groups")
    op.drop_table("groups")
    # ### end Alembic commands ###
