"""add boards and board_step_users tables

Revision ID: be920b7aff18
Revises: 8bc6fca4dff8
Create Date: 2026-03-29 19:46:37.252572

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be920b7aff18"
down_revision: Union[str, None] = "8bc6fca4dff8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "GROUP_MEMBER", "BOARD_USER", name="boardvisibility"),
            nullable=False,
        ),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_boards_created_by"), "boards", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_boards_group_id"), "boards", ["group_id"], unique=False)
    op.create_index(op.f("ix_boards_id"), "boards", ["id"], unique=False)
    op.create_index(op.f("ix_boards_name"), "boards", ["name"], unique=False)
    op.create_table(
        "board_step_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("board_id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["step_id"], ["steps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "board_id", "step_id", "user_id", name="uq_board_step_user"
        ),
    )
    op.create_index(
        op.f("ix_board_step_users_board_id"),
        "board_step_users",
        ["board_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_board_step_users_id"), "board_step_users", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_board_step_users_step_id"),
        "board_step_users",
        ["step_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_board_step_users_user_id"),
        "board_step_users",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_board_step_users_step_id"),
        "board_step_users",
        ["step_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_board_step_users_id"), "board_step_users", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_board_step_users_board_id"),
        "board_step_users",
        ["board_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_board_step_users_user_id"), table_name="board_step_users")
    op.drop_index(op.f("ix_board_step_users_step_id"), table_name="board_step_users")
    op.drop_index(op.f("ix_board_step_users_id"), table_name="board_step_users")
    op.drop_index(op.f("ix_board_step_users_board_id"), table_name="board_step_users")
    op.drop_table("board_step_users")
    op.drop_index(op.f("ix_boards_name"), table_name="boards")
    op.drop_index(op.f("ix_boards_id"), table_name="boards")
    op.drop_index(op.f("ix_boards_group_id"), table_name="boards")
    op.drop_index(op.f("ix_boards_created_by"), table_name="boards")
    op.drop_table("boards")
    # ### end Alembic commands ###
