[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os
sqlalchemy.url = sqlite:///./apps/api/step_by_step.db

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys =

[formatters]
keys =

[logger_root]
level = WARN
handlers =
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[factory_keys]

[keys]